# Generated by Django 2.1 on 2018-08-17 13:48

from django.db import migrations, models
import shopocenter.models


class Migration(migrations.Migration):

    dependencies = [
        ('shopocenter', '0003_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to=shopocenter.models.upload_to),
        ),
    ]
