# Generated by Django 2.1 on 2018-08-18 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopocenter', '0005_auto_20180818_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(blank=True, to='shopocenter.CartItem'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='qty',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
