# Generated by Django 2.1 on 2018-08-18 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopocenter', '0006_auto_20180818_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='qty',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
