# Generated by Django 2.1 on 2018-08-18 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopocenter', '0007_auto_20180818_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='items', to='shopocenter.CartItem'),
        ),
    ]
